Update conditionals.yml

diff --git a/.github/workflows/conditionals.yml b/.github/workflows/conditionals.yml
--- a/.github/workflows/conditionals.yml
+++ b/.github/workflows/conditionals.yml
@@ -6,34 +6,34 @@ on:
    branches: [main]
  # pull_request:
  #   branches: [main]
- # workflow_dispatch:
+ workflow_dispatch:
 
 jobs:
-  # when_main:
-  #  runs-on: ubuntu-latest
-  #  steps:
-  #    - name: runs when the branch is main
-  #      if: github.ref == 'refs/heads/main'
-  #      run: |
-  #       echo "runs when the branch is main"
-  #       # exit 1
+  when_main:
+   runs-on: ubuntu-latest
+   steps:
+     - name: runs when the branch is main
+       if: github.ref == 'refs/heads/main'
+       run: |
+        echo "runs when the branch is main"
+        # exit 1
 
-  #    - name: only runs when the previous step failed
-  #      if: failure()
-  #      run: echo "Previous step failed....."
+     - name: only runs when the previous step failed
+       if: failure()
+       run: echo "Previous step failed....."
 
-  on-push:
-    if: github.event_name != 'pull_request'
-    runs-on: ubuntu-latest
-    steps:
-      - name: only run on push events
-        run: echo "Only run on push events"
+  # on-push:
+  #   if: github.event_name != 'pull_request'
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: only run on push events
+  #       run: echo "Only run on push events"
         
-      - name: step with continue-on-error
-        run: |
-          echo "This step will fail"
-          exit 1
-        continue-on-error: true
+  #     - name: step with continue-on-error
+  #       run: |
+  #         echo "This step will fail"
+  #         exit 1
+  #       continue-on-error: true
 
       - name: next step after failure
         run: echo "Workflow continues even after failure"
