Update conditionals.yml

diff --git a/.github/workflows/conditionals.yml b/.github/workflows/conditionals.yml
--- a/.github/workflows/conditionals.yml
+++ b/.github/workflows/conditionals.yml
@@ -9,25 +9,25 @@ on:
  workflow_dispatch:
 
 jobs:
-  when_main:
-   runs-on: ubuntu-latest
-   steps:
-     - name: runs when the branch is main
-       if: github.ref == 'refs/heads/main'
-       run: |
-        echo "runs when the branch is main"
-        exit 1
+  # when_main:
+  #  runs-on: ubuntu-latest
+  #  steps:
+  #    - name: runs when the branch is main
+  #      if: github.ref == 'refs/heads/main'
+  #      run: |
+  #       echo "runs when the branch is main"
+  #       # exit 1
 
-     - name: only runs when the previous step failed
-       if: failure()
-       run: echo "Previous step failed....."
+  #    - name: only runs when the previous step failed
+  #      if: failure()
+  #      run: echo "Previous step failed....."
 
-  # on-push:
-  #   if: github.event_name != 'pull_request'
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: only run on push events
-  #       run: "Only run on push events"
-  #       # continue-on-error: true
+  on-push:
+    if: github.event_name != 'pull_request'
+    runs-on: ubuntu-latest
+    steps:
+      - name: only run on push events
+        run: "Only run on push events"
+        # continue-on-error: true
    
      
