Update conditionals.yml

diff --git a/.github/workflows/conditionals.yml b/.github/workflows/conditionals.yml
--- a/.github/workflows/conditionals.yml
+++ b/.github/workflows/conditionals.yml
@@ -16,11 +16,11 @@ jobs:
        if: github.ref == 'refs/heads/main'
        run: |
         echo "runs when the branch is main"
-        # exit 1
+        exit 1
 
-  #    - name: only runs when the previous step failed
-  #      if: failure()
-  #      run: echo "Previous step failed....."
+     - name: only runs when the previous step failed
+       if: failure()
+       run: echo "Previous step failed....."
 
   # on-push:
   #   if: github.event_name != 'pull_request'
