Update conditionals.yml

diff --git a/.github/workflows/conditionals.yml b/.github/workflows/conditionals.yml
--- a/.github/workflows/conditionals.yml
+++ b/.github/workflows/conditionals.yml
@@ -28,6 +28,12 @@ jobs:
     steps:
       - name: only run on push events
         run: echo "Only run on push events"
-        # continue-on-error: true
-   
-     
+        
+      - name: step with continue-on-error
+        run: |
+          echo "This step will fail"
+          exit 1
+        continue-on-error: true
+
+      - name: next step after failure
+        run: echo "Workflow continues even after failure"
