Update exclude-fail-fast.yml

diff --git a/.github/workflows/exclude-fail-fast.yml b/.github/workflows/exclude-fail-fast.yml
--- a/.github/workflows/exclude-fail-fast.yml
+++ b/.github/workflows/exclude-fail-fast.yml
@@ -1,8 +1,7 @@
 name: matrix build os
 
 on:
-  push:
-    branches: [main]
+ workflow_dispatch:
 
 jobs:
   exclude-fall-fast:
@@ -27,6 +26,6 @@ jobs:
       - name: Print Python Version
         run: python --version
 
-      - name: Trigger failure
-        if: matrix.python-version == '3.11'
-        run: exit 1
+      # - name: Trigger failure
+      #   if: matrix.python-version == '3.11'
+      #   run: exit 1
