intentionally break workflow for testing

diff --git a/.github/workflows/hello.yml b/.github/workflows/hello.yml
--- a/.github/workflows/hello.yml
+++ b/.github/workflows/hello.yml
@@ -41,3 +41,7 @@ jobs:
       - name: Print runner OS
         run: |
           echo "Runner OS: ${{ runner.os}}"
+
+      # Step 6 Intentionally fail    
+      - name: Break the workflow on purpose
+        run: exit 1
